default_platform(:mac)

platform :mac do
  lane :local do

    # check_apple_agreement(
    #   apple_id: "ospfranco@protonmail.com",
    #   password: ENV["FASTLANE_PORTAL_PASSWORD"]
    # )

    Dir.chdir("..") do
      sh("bun", "bump")
    end

    version = get_version_number(xcodeproj: "./macos/sol.xcodeproj")

    path = "/Users/robert/src/robertarles/sol/"
    appFileName = path + "Sol.app"
    zipFileName = path + "releases/local/" + version + ".zip"
    
    gym(
      scheme: "release",
      configuration: "Release",
      clean: true,
      workspace: "./macos/sol.xcworkspace",
      output_directory: path,
      export_method: "development"
    )

    # notarize(
    #   package: appFileName,
    #   bundle_id: "us.arles.sol",
    #   username: "robert@arles.us",
    #   asc_provider: "AH3T5F47R4"
    # )

    zip(
      path: appFileName,
      output_path: zipFileName,
      symlinks: true
    )

    # set_github_release(
    #   repository_name: "robertarles/sol",
    #   api_token: ENV["GITHUB_API_TOKEN"],
    #   tag_name: version,
    #   is_generate_release_notes: true,
    #   upload_assets: [zipFileName]
    # )

    #release_notes = lane_context[SharedValues::SET_GITHUB_RELEASE_JSON]["body"]

    #file_url = "https://github.com/robertarles/sol/releases/download/" + version + "/" + version + ".zip"
    
    
    Dir.chdir("..") do
      #sh("./macos/Pods/Sparkle/bin/generate_appcast", "releases")

      #sh("./scripts/appcast.js", file_url, version, release_notes)

      Dir.glob("#{path}releases/local/*.zip").each { |file| File.delete(file) }

      sh("git", "add", ".")
      if !sh("git", "diff", "--cached", "--quiet", exception: false)
        sh("git", "commit", "-m", "local " + version)
        sh("git", "push")
      else
        puts "No git changes to commit"
      end
    end

    sh("cp", "-R", appFileName, "/Applications/")
    sh("killall", "Sol")
    sh("open", "/Applications/Sol.app")

    #sh("pingme", "Sol " + version + " released")
  end

  lane :release do

    # check_apple_agreement(
    #   apple_id: "ospfranco@protonmail.com",
    #   password: ENV["FASTLANE_PORTAL_PASSWORD"]
    # )

    Dir.chdir("..") do
      sh("bun", "bump")
    end

    version = get_version_number(xcodeproj: "./macos/sol.xcodeproj")

    path = "/Users/robert/src/robertarles/sol/"
    appFileName = path + "Sol.app"
    zipFileName = path + "releases/" + version + ".zip"
    
    gym(
      scheme: "release",
      configuration: "Release",
      clean: true,
      workspace: "./macos/sol.xcworkspace",
      output_directory: path,
      export_method: "development"
    )

    notarize(
      package: appFileName,
      bundle_id: "us.arles.sol",
      username: "robert@arles.us",
      asc_provider: "AH3T5F47R4"
    )

    zip(
      path: appFileName,
      output_path: zipFileName,
      symlinks: true
    )

    set_github_release(
      repository_name: "robertarles/sol",
      api_token: ENV["GITHUB_API_TOKEN"],
      tag_name: version,
      is_generate_release_notes: true,
      upload_assets: [zipFileName]
    )

    release_notes = lane_context[SharedValues::SET_GITHUB_RELEASE_JSON]["body"]

    file_url = "https://github.com/robertarles/sol/releases/download/" + version + "/" + version + ".zip"
    
    
    Dir.chdir("..") do
      sh("./macos/Pods/Sparkle/bin/generate_appcast", "releases")

      sh("./scripts/appcast.js", file_url, version, release_notes)

      Dir.glob("#{path}releases/*.zip").each { |file| File.delete(file) }

      sh("git", "add", ".")
      sh("git", "commit", "-m", version)
      sh("git", "push")
    end

    sh("cp", "-R", appFileName, "/Applications/")

    sh("open", "/Applications/Sol.app")

    sh("pingme", "Sol " + version + " released")
  end
end
